# Configurations for running the modules

AIRLINE_RESERVATION_HOST="localhost"
AIRLINE_RESERVATION_PORT=9091
TRAVEL_AGENCY_SERVICE_PORT=9090

EMAIL_SERVICE_HOST="localhost"
EMAIL_SERVICE_PORT=8082
EMAIL_SENDER_ADDR="virgin-travels@bookings.com"

MAIL_SMTP_HOST="smtp.mailtrap.io"
MAIL_SMTP_AUTH_USERNAME="admin"
MAIL_SMTP_AUTH_PASSWORD="admin"
