# Configurations for testing the modules

AIRLINE_RESERVATION_HOST="localhost"
AIRLINE_RESERVATION_PORT=9092
TRAVEL_AGENCY_SERVICE_PORT=9093

EMAIL_SERVICE_HOST="localhost"
EMAIL_SERVICE_PORT=8083
EMAIL_SENDER_ADDR="virgin-travels@bookings.com"

MAIL_SMTP_HOST="smtp.serveraddress.com"
MAIL_SMTP_AUTH_USERNAME="test"
MAIL_SMTP_AUTH_PASSWORD="test"
